### ISSUE TITLE
Deftest ovveride assert_equals

### ISSUE THREAD

**Issue by d954mas** [britzl/deftest#3]
1)It was surprise find that deftest add some new asserts(same,unique) and ovverided equals. Plz add info about that in doc.
2)Equals should log all values, as default impl do. Without, it hard to understand what wrong.

```lua
telescope.make_assertion(
	"equal",
	function(_, ...) return telescope.assertion_message_prefix .. "all values to be equal (using the equality operator)" end,
	function(...) return check.equal(...) end
)

**Comment by britzl** [comment]
Good point. I've updated the docs with this information.

I don't have time to do 2 right now though.

**Comment by d954mas** [comment]
Thanks. I will try impl that logging, when I will need it)
